import uuid
from sqlalchemy import Column, String, ForeignKey, Text, DateTime, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.config.database import Base

class GoogleDriveImageCaption(Base):
    __tablename__ = "google_drive_image_captions"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    google_drive_account_id = Column(String, ForeignKey("google_drive_accounts.id", ondelete="CASCADE"), nullable=False)
    file_id = Column(String, ForeignKey("google_drive_files.file_id", ondelete="CASCADE"), nullable=False, unique=True)
    
    # Caption generated by Gemini
    caption = Column(Text, nullable=False)
    
    # ChromaDB document ID for vector retrieval
    chroma_doc_id = Column(String, nullable=False, unique=True)
    
    # Store metadata for debugging/reference
    file_metadata = Column(JSON, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    file = relationship("GoogleDriveFile", foreign_keys=[file_id])
