"""add new one drive models

Revision ID: 932c882038be
Revises: b28a694cea33
Create Date: 2026-01-08 18:28:29.426905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932c882038be'
down_revision: Union[str, Sequence[str], None] = 'b28a694cea33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_drive_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('onedrive_account', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onedrive_account')
    )
    op.create_table('one_drive_folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('one_drive_account_id', sa.String(), nullable=False),
    sa.Column('folder_name', sa.String(), nullable=False),
    sa.Column('folder_parents', sa.String(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['one_drive_account_id'], ['one_drive_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_drive_folders_trees',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('one_drive_account_id', sa.String(), nullable=False),
    sa.Column('folder_tree', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['one_drive_account_id'], ['one_drive_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('one_drive_account_id')
    )
    op.create_table('one_drive_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('one_drive_account_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_parents', sa.String(), nullable=False),
    sa.Column('file_created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('md5Checksum', sa.String(), nullable=True),
    sa.Column('mimeType', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('last_modified_time', sa.DateTime(), nullable=True),
    sa.Column('webViewLink', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_parents'], ['one_drive_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['one_drive_account_id'], ['one_drive_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one_drive_files')
    op.drop_table('one_drive_folders_trees')
    op.drop_table('one_drive_folders')
    op.drop_table('one_drive_accounts')
    # ### end Alembic commands ###
